# Generated by Django 5.0.2 on 2024-02-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_courses_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(through='api.Enrollment', to='api.course'),
        ),
    ]
