# Generated by Django 5.0.2 on 2024-02-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='department',
            new_name='departmentID',
        ),
    ]
